plaid/react-native-plaid-link-sdk

- ios/RNLinksdk.m
paymentToken should be paymentTokenInput
fixes #54
> fixes paymentToken is undefined

- README.md
copy and pasting the documentation caused me hours of headache because the import of `Text` component was wrong
> fix wrong Text import

- PlaidLink.js
Relax the prop validation in preparation for one-time tokens, which will be released in beta soon.
> Update props to accept an item_add_token in lieu of public_key

- ios/RNLinksdk.m
> Fix for iOS build failure.

- android/src/main/java/com/plaid/PlaidModule.kt
Plog isn't available, use normal Logs
> [RN]: Fix Plog

- README.md
Badge is automatically updated to latest Cocoapods version.
> Add badge with latest iOS version

- PlaidLink.js
- android/build.gradle
- android/src/main/java/com/plaid/PlaidModule.kt
Android 2.0 introduces new breaking changes. This PR ensures that RN is likewise updated
> ANDROID-327: Update RN to use Android 2.0

- android/build.gradle
- package.json
Bumped RN version to 4.1.0 as well
> Updated Android to 2.1.0

- README.md
update the docs to remove mention of the public_key and replace with link tokens
> update readme for link token

- PlaidLink.js
- README.md
I added an event emitter hook for react functional components. Also added instructions on how to use it in the readme
> Event emitter hook

- PlaidLink.js
- android/src/main/java/com/plaid/PlaidModule.kt
Payment token is now passed in through the token field along with other token types.
> Remove Payment Token

- ios/RNLinksdk.m
Exit:  {"error": {"display_message": "", "error_code": "INTERNAL_SERVER_ERROR", "error_message": "an unexpected error occurred", "error_type": "API_ERROR"}, "metadata": {"institution": {"institution_id": "ins_5", "name": "Citi"}, "link_session_id": "<redacted>", "metadata_json": "{\"display_message\":null,\"error_code\":\"INTERNAL_SERVER_ERROR\",\"error_message\":\"an unexpected error occurred\",\"error_type\":\"API_ERROR\"}", "request_id": "<redacted>", "status": "requires_credentials"}}
> iOS: Return error in Exit

- package.json
- tsconfig.json
Add typescript dependencies and a tsconfig file so that we can begin adding types
> Added typscript dependencies

- ios/RNLinksdk.m
**consistent keys**
android 🤝 iOS
> institution.name -> institution.institution_name

- package.json
- react-native-plaid-link-sdk.podspec
Also require 2.0.5 LinkKit SDK
> RN: Update version to v6.0.3-rc1

- PlaidLink.tsx
- package.json
- types/Types.d.ts
Convert the Plaid file to typescript and use the new types for defining the component and hook to open Plaid Link. The component is now a `Pressable`.
> Converted Plaid.js to tsx

- example/ios/Podfile
- example/yarn.lock
> Use standard registry for example dependencies

- .npmignore
Introduce npmignore file to ignore the example app. If customers want to check out the example, they can directly download from our GitHub.
> RN: Add .npmignore file

- .gitignore
- example/components/HomeScreen.tsx
- example/components/PlaidLink.tsx
- package.json
Updated gitignore, removed console log, removed token, and updated version
> Minor updates

- Types.ts
- android/src/main/java/com/plaid/PlaidModule.kt
- package.json
Fix Product, Log Level and Extra Params for Android
> Fix Product, Log Level and Extra Params

- PlaidLink.tsx
- Types.ts
- android/src/main/java/com/plaid/PlaidModule.kt
- example/components/PlaidLink.tsx
- package.json
Classes will allow us to have a strongly typed system that matches Android & iOS.  This also updates the parsing of the json in the Android native module.
> Update Account Subtype Typing Using Classes

- android/src/main/java/com/plaid/PlaidModule.kt
- package.json
Update the min versions and use a loop for android
> Fix Release

- android/src/main/java/com/plaid/PlaidModule.kt
Change return value of getLinkLogLevel, oops
> Android: Change return value of LinkLogLevel

- README.md
Update the README to reflect changes for v7.
> Updated README [HOLD FOR RELEASE]

- README.md
Improve readme reference to upgrade instructions
> Improve upgrade instructions

- README.md
- Add a disclaimer to the readme that 7.x.x is still under development
- Fix a few doc inconsistency
- Group all version information
> Add RC disclaimer and clean up docs

- android/src/main/java/com/plaid/gson/PlaidJsonConverter.kt
- android/src/main/java/com/plaid/gson/RNLinkInstitutionAdapter.kt
Change institution_name to name and institution_id to id
> ANDROID: Update Institution object fields

- ios/RNLinksdk.m
> Use fractional seconds with ISO8601 date formatter

- PlaidLink.tsx
> Revert to TouchableOpacity for RN backward compatibility

- Types.ts
- ios/RNLinksdk.m
This helps us with consistency across all 4 platforms (Web, Android, iOS, and RN)
> RN: Change field from errorDisplayMessage to displayMessage

- README.md
Bump needed iOS version to 2.0.11
Change status to Active
> RN: Update README Version compatibility table

- example/ios/Podfile.lock
- example/ios/plaidRNDemo.xcodeproj/project.pbxproj
- example/package.json
Increase iOS minimum deployment target to 11 to satisfy LinKKit requirement
> Update react-native-plaid-link-sdk dependency in example to 7.1.0

- example/package.json
> Bump version of example app to 7.2.0

- README.md
> Remove obsoleted Run Script step on iOS

- android/build.gradle
- android/src/main/AndroidManifest.xml
- ios/RNLinksdk.m
- package.json
> RN: v7.2.1

- Types.ts
https://github.com/plaid/react-native-plaid-link-sdk/issues/465
> RN: Add selection to LinkEventMetadata

- example/ios/Podfile.lock
- example/package.json
- ios/RNLinksdk.m
- ios/RNLinksdk.m-e
- package.json
- react-native-plaid-link-sdk.podspec
These iOS & example project changes are necessary for the RN 7.4.0 release
> v7.4.0 ios changes

- README.md
- example/ios/plaidRNDemo/AppDelegate.m
Updates iOS Deep Linking examples to use most up to date APIs
> Update examples & docs to use up to date APIs

- android/build.gradle
- example/android/build.gradle
- example/package.json
Android v3.9.0 and also remove the jcenter dependency
> Upgrade to Android v3.9.0

- android/build.gradle
- android/src/main/AndroidManifest.xml
- ios/RNLinksdk.m
- ios/RNLinksdk.m-e
- package.json
- react-native-plaid-link-sdk.podspec
Prepare new react native release
- Adds support for identity verification events
- Updates Android SDK to latest version 3.10.1
- Updates iOS SDK to latest version 3.1.0
> React Native 8.0.0

- ios/RNLinksdk.m
Adds missing `PLKEventNames` and `PLKViewNames`
> Update view and event names

- README.md
- example/ios/plaidRNDemo/AppDelegate.m
Updated the readme and example to no longer call continue.
> Remove outdated iOS Documentation and Example Code

- README.md
- android/build.gradle
- android/src/main/AndroidManifest.xml
- ios/RNLinksdk.m
- package.json
- react-native-plaid-link-sdk.podspec
- Bumps Android SDK to 3.12.0
- Bumps iOS SDK to 4.3.0
> [Release] - 10.2.0 

- .gitignore
- .npmignore
- CHANGELOG.md
- README.md
- android/src/main/AndroidManifest.xml
- ios/RNLinksdk.m
- package.json
Resolves https://github.com/plaid/react-native-plaid-link-sdk/issues/565
https://github.com/plaid/react-native-plaid-link-sdk/issues/565
Select one:
> Release 10.6.1

- CHANGELOG.md
- README.md
- android/src/main/AndroidManifest.xml
- ios/RNLinksdk.m
- package.json
> Prep Release 10.7.0

- CHANGELOG.md
- README.md
- android/src/main/AndroidManifest.xml
- android/src/main/java/com/plaid/gson/RNAccountAdapter.kt
- ios/RNLinksdk.m
- package.json
- react-native-plaid-link-sdk.podspec
Update iOS SDK to [4.7.0](https://github.com/plaid/plaid-link-ios/releases/tag/4.7.0)
> [Release] 10.8.0

- example/android/app/build.gradle
- example/package-lock.json
- example/package.json
- package-lock.json
Updates example app to use `11.0.1` and resolves duplicate class error on android.
> Chore update example 11.0.1

- CHANGELOG.md
- README.md
- android/src/main/AndroidManifest.xml
- ios/RNLinksdk.m
- package.json
- src/Types.ts
- Export `LinkAccountSubtypes`
Select one:
> [Release] - 11.0.2

- example/ios/Podfile
- example/ios/Podfile.lock
- example/ios/plaidRNDemo.xcodeproj/project.pbxproj
- example/package-lock.json
- example/package.json
> update to linkKit 11.1.0

- CHANGELOG.md
- android/build.gradle
- android/src/main/AndroidManifest.xml
- ios/RNLinksdk.m
- package.json
> [Release] - 11.2.0

- CHANGELOG.md
- README.md
- android/build.gradle
- android/src/main/AndroidManifest.xml
- ios/RNLinksdk.m
- package.json
- react-native-plaid-link-sdk.podspec
Release 10.10.0 
- Updates Android SDK to `3.14.2`
- Updates iOS SDK to `4.7.1`
| React Native | >= [66.0](https://reactnative.dev/blog/2021/10/01/version-066) |
- Update iOS SDK to [4.7.1](https://github.com/plaid/plaid-link-ios/releases/tag/4.7.1)
Android SDK [3.14.2](https://github.com/plaid/plaid-link-android/releases/tag/v3.14.2)
- Stability Improvements.
iOS SDK [4.7.1](https://github.com/plaid/plaid-link-ios/releases/tag/4.7.1)
| Xcode | >= 14.0 |
| iOS | >= 11.0 |
- Stability Improvements.
> [Release] - 10.10.0

- example/ios/Podfile.lock
- example/package-lock.json
- example/package.json
Updates demo app to use latest SDK
> update LinkKit to v10.11.0

- example/ios/Podfile.lock
- example/package-lock.json
- example/package.json
Update example app to use latest version of SDK
> update example to 11.3.0

- CHANGELOG.md
- README.md
- android/build.gradle
- android/src/main/AndroidManifest.xml
- ios/RNLinksdk.m
- package.json
Updates Android SDK to [4.1.1](https://github.com/plaid/plaid-link-android/releases/tag/v4.1.1)
> [Release] - 11.4.0

- CHANGELOG.md
- README.md
- android/src/main/AndroidManifest.xml
- ios/RNLinksdk.m
- package.json
- react-native-plaid-link-sdk.podspec
| React Native | >= [66.0](https://reactnative.dev/blog/2021/10/01/version-066) |
- Updates iOS SDK to 4.7.2.
Android SDK [3.14.3](https://github.com/plaid/plaid-link-android/releases/tag/v3.14.3)
iOS SDK [4.7.2](https://github.com/plaid/plaid-link-ios/releases/tag/4.7.2)
| Xcode | >= 14.0 |
| iOS | >= 11.0 |
> [Release] 10.13.0

- README.md
Fixing two incorrectly listed Android release versions.
> Update README.md Release Table to correct Android Release Versions 

- example/ios/Podfile.lock
- example/package-lock.json
- example/package.json
- example/src/Screens/PlaidLinkScreen.tsx
- Add submit button to example to test layer.
- Updates example to latest SDK version
> [Chore] Update Example

- ios/PLKEmbeddedViewComponentView.mm
We at [Software Mansion](https://swmansion.com/) have been working on [improving support](https://blog.swmansion.com/sunrising-new-architecture-in-the-new-expensify-app-729d237a02f5) for the new architecture for quite a while now. If you need help with anything related to New Architecture, like:
- [migrating your library](https://x.com/swmansion/status/1717512089323864275)
- [migrating your app](https://github.com/Expensify/App/pull/13767)
- [investigating issues](https://github.com/facebook/react-native/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Aj-piasecki+is%3Aopen)
- [improving performance](https://x.com/BBloniarz_/status/1808138585528303977)
or you just want to ask any questions, hit us up on [projects@swmansion.com](mailto:projects@swmansion.com)
---
PR adding `load` method needed …
> feat: add load method

- CHANGELOG.md
- README.md
- android/src/main/AndroidManifest.xml
- ios/PLKFabricHelpers.h
- ios/RNLinksdk.mm
- package.json
- Fix PLKFabricHelpers.h import for RCT_NEW_ARCH_ENABLED
> [Fix] - Issue 713

- FabricExample/package-lock.json
- FabricExample/package.json
- example/package-lock.json
- example/package.json
Removes the name and version from both example `package.json` files
> [Chore] - Remove name and version from example package files

- README.md
- android/src/main/java/com/plaid/PlaidModule.kt
- android/src/paper/java/com/plaid/NativePlaidLinkModuleAndroidSpec.java
- src/PlaidLink.tsx
- src/fabric/NativePlaidLinkModuleAndroid.ts
- src/index.ts
- tsconfig.json
- Add destroy API to clear session state and memory on Android.
> Destroy Api (Android only)

- example/ios/Podfile.lock
- example/package-lock.json
- example/package.json
Updates example app to v12.3.0
> [Chore] - update example to 12.3.0

- example/ios/Podfile.lock
- example/package.json
- example/src/Screens/FinanceKitScreen.tsx
Updates FinanceKit Usage in the Example app
> [Feat] - Update FinanceKit in Example App
