plaid/react-native-plaid-link-sdk

PlaidLink.js, index.js
This PR allows the developers to customize the CTA that opens PlaidLink modal to match each app UI/UX.
Specifically:
- Changed the component to be a `TouchableOpacity`
- Removed `className` prop since is not valid for React Native (it only works for ReactJS) and added a `style` prop instead
- Added `testID` prop to be passed same as `accessibilityLabel`
By doing this you can instance the component as follows:
```
<PlaidLink
publicKey='<# Your Public Key #>'
clientName='<# Your Client Name #>'
env='<# Environment #>'  // 'sandbox' or 'development' or 'production'
onSuccess={e => console.log('success: ', e)}
product={['<# Product #>']}
style={styles.button}>
<Text style={styles.text}> Add Account </Text>
</PlaidLink>
```
=> Allow PlaidLink component customization and export openLink

ios/RNLinksdk.m
fixes #57 
better code would be something like:
```
self.linkViewController.modalPresentationStyle = UIModalPresentationStyle.UIModalPresentationFullScreen;
```
but i don't know objective-c and ios that much so i dont know what header to import to get the `UIModalPresentationStyle`
hardcoding to `0` since `UIModalPresentationStyle` is `0` in the enum. see:
https://developer.apple.com/documentation/uikit/uimodalpresentationstyle/uimodalpresentationfullscreen?language=objc
=> defaults to FullScreen mode

android/build.gradle, android/src/main/java/com/plaid/PlaidModule.kt
The oauthNonce parameter was not being passed from the PlaidModule into the Android SDK.  With this parameter passed in, we will now have oauth support on Android.
=> Added oauth support for android

android/src/main/java/com/plaid/PlaidModule.kt
onActivityResult was being triggered from Intents not started by Plaid. I have added a check to ignore invoking the callback function if the resultCode does not belong to Plaid's resultCodes.
=> added check to ignore result if onActivityResult is not triggered by Plaid

PlaidLink.js, index.js, ios/RNLinksdk.m
This PR allows OAuth flows on iOS to dismiss any existing link view controller when re-opening plaid after an applink callback.
Fixes #63
=> Expose dismissLink method.

PlaidLink.js, android/build.gradle, android/src/main/java/com/plaid/PlaidModule.kt, ios/RNLinksdk.m
Expose a property on the PlaidLink component for account subtype filtering.  In iOS this property is directly consumed.  On Android this property is not exposed yet so we use extra params until the next sdk release.
=> Add support for account subtype filtering

android/build.gradle, android/gradle.properties, android/gradle/wrapper/gradle-wrapper.properties, android/src/main/java/com/plaid/PlaidModule.kt
Updates dependencies for Android 1.3.0.   Also addresses the 1.3.0 breaking change which renamed `LinkConfiguration.publicToken` to `LinkConfiguration.token` internally.  Externally, we still expose `publicToken`
=> Update to Android 1.3.0

android/build.gradle, android/src/main/java/com/plaid/PlaidModule.kt
Right now users have to pass in different fields for Android and iOS: https://github.com/plaid/react-native-plaid-link-sdk/pull/111/files
Ideally they pass `token` to both platforms, and with Android Link SDK using `token` in 1.3.0, we can.
Also added change to simplify passing string fields to LinkConfiguration:
Not really saving that many lines, but at least reducing potential future errors where we copy and paste that block and forget to change fieldName in each part.
💚 How did you test it?
Ran LinkSdkSample
=> RN: Change Android public_token to token

ios/RNLinksdk.m
[LinkKit version 1.1.31](https://github.com/plaid/plaid-link-ios/releases/tag/ios%2F1.1.31) adds support for a new Plaid flow which deprecates the public_key (see [Link Token Migration Guide](https://plaid.com/docs/link-token-migration-guide/) for details).
This PR adds support for item-add-tokens to the react-native bridge to LinkKit.
=> Add support to handle item-add tokens

android/src/main/java/com/plaid/PlaidModule.kt
Oauth nonce no longer needs to be passed in on Android
=> RN: Remove oauthnonce

README.md
We need to include the okhttp3 version 4.x because RN hardcodes 3.12.1 while the internal Android sdk uses 4.2.1
Adding this line will fix the errors while we investigate a long-term solution.
=> Update  to include okhttp3 dependency

PlaidLink.js
Rationale: iOS had a check to see if the error handler was null before returning a result, whereas Android didn't. Adding this makes both platforms behave similarly.
Fixes issue #151
=> Don't crash when no error handler

PlaidLink.js, android/src/main/java/com/plaid/PlaidModule.kt, ios/RNLinksdk.m
- Makes required configs optional (because of server-side configs). I was unable to make the props optional with xor behavior because this repo does not yet use typescript.
- If a link token is used, construct the proper configs for both Android and iOS.
TODO:
=> support server-side config changes for Android and iOS

PlaidLink.js, ios/RNLinksdk.m
Hi,
This is a draft PR to upgrade the RN SDK to rely on iOS v2. I'm putting it up as a draft to start discussion around how we want to surface the new continueFromRedirectUri API in LinkKit v2 through RN.
I see a few potential options:
1. A native method for continuingFromRedirectUri and guidance for integrators to call that method from their AppDelegate
2. A method bridged to JS (as in this PR), and expose that method through PlaidLink.js – I'm not sure if the Javascript layer of our integrators' apps already has the requisite redirect URI in scope.
3. An additional prop (e.g., `recievedRedirectUri`) that results in RNLinksdk calling continue in its internal create method.
--
The TODOs will be addressed in a commit, I wanted to get this PR out in Draft mode ASAP to facilitate discussion.
=> Upgrade to iOS LinkKit v2.0.0

PlaidLink.js
iOS v2+ doesn't use the state ID
=> Remove unused prop

PlaidLink.js, README.md
=> Fix 198 prop type and docs

README.md
Directly specifying the Android SDK dependency is redundant, this is already provided transitively through the Plaid RN SDK.
=> Remove instruction to add direct dependency on Android SDK

PlaidLink.tsx
Quick patch on top of https://github.com/plaid/react-native-plaid-link-sdk/pull/255 where we missed to unpack the properties and only provide a single configuration into Link.
=> Choose what config to pass into link

android/build.gradle
Port of build type changes in https://github.com/plaid/react-native-plaid-link-sdk/pull/259 to be able to test the fix without dependency on an unreleased SDK version.
=> Define build types explicitly to satisfy our internal CI

android/src/main/java/com/plaid/PlaidModule.kt, android/src/main/java/com/plaid/gson/PlaidJsonConverter.kt, android/src/main/java/com/plaid/gson/RNAccountAdapter.kt, example/App.tsx, example/android/app/build.gradle, example/components/ExitScreen.tsx, example/components/HomeScreen.tsx, example/components/PlaidLink.tsx, example/components/SuccessScreen.tsx, package.json
Updated the sample app to type the inputs and outputs. Also rename the error screen to the exit screen to match the type that is returned.
This uncovered several bugs on the Android side which were also fixed:
1. Return the writeable map directly instead of putting it in another map under the "data" key"
1. Change gson to not snake case fields
1. set type and subtype to nullable in the account gson adapter
=> Update example bindings

example/android/app/build.gradle
We no longer need to specify the android sdk version or the okhttp dependency
=> Updated sample build.gradle

android/src/main/java/com/plaid/gson/RNAccountAdapter.kt
If verification status was null we were serializing it to "null" as a string then trying to convert it to a json object.  Instead we should only serialize the status if it is not null to begin with
=> Fix verification status deserialization

android/src/main/AndroidManifest.xml, check_version_hook.js, check_version_hook.sh, package.json
Problem: the react native version hardcoded in the Android SDK was out of date with the current version in `package.json`
Solution: add a pre-commit hook that checks whether both versions are aligned and only allows to commit when that's the case.
=> Add commit hook to align react native version with Android version

Types.ts, ios/RNLinksdk.m
1. LinkAccountSubtypeInterface seems like an unfortunate name to publicize when LinkAccountSubtype is no longer private
2. Updating the iOS code to parse the newly formatted account subtypes
=> Cleanup LinkAccountSubtype interface and update iOS bridge code to support new account subtype format

PlaidLink.tsx, ios/RNLinksdk.m, react-native-plaid-link-sdk.podspec
Changed the approach of piping from the native layer to the JS layer to be more similar to Android, which is to pipe to two listeners from the objective-C layers’ onSuccess and onExit.
Thus, we indirectly rely on Objective C’s type system
Test plan:
LinkSuccess with user_good, pass_good returns in onSuccess
Success:  
```
{
"metadata": {
"accounts": [[Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object]],
"institution": {
"id": "ins_6",
"name": "US Bank"
},
"linkSessionId": "e26f9ae7-45d3-400f-a953-67438c5e080a",
"metadataJson": "{<TRUNCATED>"
},
"publicToken": "public-sandbox-499010af-7e82-46ca-8725-ece3e823c7f9"
}
```
LinkExit returns in onExit
Exit:  
```
{
"error": {
"errorCode": "",
"errorDisplayMessage": "",
"errorMessage": "",
"errorType": ""
}, …
```
=> IOS: Return LinkSuccess in onSuccess

android/src/main/AndroidManifest.xml, package.json
Convert `react-native` and `react` to be a peer dependency instead of a normal dependency. This will cause build errors on dependency conflicts instead of ending up with two different versions of the same module in the host application.
To learn more about peer dependencies, have a look at [this article](https://medium.com/angular-in-depth/npm-peer-dependencies-f843f3ac4e7f).
On top this also loosens our restrictions on `react-native` and `react` versions, for instance:
```
"peerDependencies": {
"react": "*", // Let react-native decide the version
"react-native": ">=0.61" // released Sept 2019
},
```
This potentially fixes https://github.com/plaid/react-native-plaid-link-sdk/issues/295
-----------------------------------------
Tested this with a a sample project using a different version …
=> Reduce dependency conflicts

react-native-plaid-link-sdk.podspec
Latest Xcode 12 fails to build while without a module to depend on React-Core directly hence this change is necessary for all native modules on iOS. For more details please check: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
Use this branch to install with an app running on Xcode 12.
=> fix: Xcode 12 compatibility

Types.ts
Feel free to close if the usage of `String` was intentional
=> change `String` types to `string` for string literals

README.md
Update readme to explicitly state that autolinking isn't supported for Android.
This isn't an issue on iOS as we aren't using TurboModules on iOS.
Also moved all links in readme to bottom of page.
=> Make explicit that autolinking isn't supported for Android

PlaidLink.tsx
We used to have a deprecation log for public keys, but accidentally removed that in `7.0.0`.
This PR brings that back.
Tested by opening Link with public key and see warning in console, opening Link with no token yielded no warning.
Triggered by https://github.com/plaid/react-native-plaid-link-sdk/issues/328
=> Add deprecation log

Types.ts, ios/RNLinksdk.m
Addresses part of the comment on [326](https://github.com/plaid/react-native-plaid-link-sdk/issues/326) and the fact that the `LinkEventName` typing currently has lowercase fields (though the actual `LinkEvent` object has an uppercase `eventName` field)
=> updating LinkEventName and LinkError typings

ios/RNLinksdk.m
Using the new dismissalHandler API, we can keep the existing cleanup code in -dismiss while preventing another call to dismissing the view controller from being initiated by LinkKit.
Closes #227
=> (Change base branch to main once bridgePublicTokens lands) – Ensure the dismissal logic is only invoked once

ios/RNLinksdk.h
RN: Check for <React/RCTBridgeModule> instead
https://github.com/plaid/react-native-plaid-link-sdk/issues/436
=> RN: Check for <React/RCTBridgeModule> instead of "RCTBridgeModule"

ios/RNLinksdk.m
This adds mapping for the `BANK_INCOME_INSIGHTS_COMPLETED` event from the iOS 2.3.2 release
=> Add `BANK_INCOME_INSIGHTS_COMPLETED` event

example/ios/Podfile.lock, example/package.json
This adds back explicit example project dependencies the iPS example app requires, and commits the `Podfile.lock` changes associated with installing the iOS dependencies.
=> Add explicit deps to example project

PlaidLink.tsx
export `continueFromRedirectUriString` for custom implementations
avoid usage of deprecated api if possible
Resolves #441
=> feat: export redirect, update unsubscribe

.npmignore
If `.npmignore` is used, `.gitignore` is ignored by npm. `android/build` is published on npm. This change will fix that.
It'll reduce the npm package size from 9MB to less than 180KB
=> Add most gitignore records to npmignore

README.md, example/ios/plaidRNDemo/AppDelegate.m
Our docs were not explicit about how to set up deep link handling, which is necessary for OAuth bank connections
=> Add iOS OAuth docs

android/build.gradle
In PR #490, a plus was added in front of `mavenCentral()`. This commit removes the plus.
I would greatly appreciate it if this gets merged and released ASAP, since no android app can be built with `jcenter()`.
=> Remove '+' from build.gradle

android/build.gradle, android/src/main/AndroidManifest.xml, ios/RNLinksdk.m, package.json
<h1 align="center">
</h1>
kotlin gradle plugin is deprecated for rn 0.71
=> update kotlin graddle plugin to supports rn 0.71

Types.ts
extends support for https://plaid.com/docs/link/react-native/#link-react_native-onevent-eventName-BANK-INCOME-INSIGHTS-COMPLETED, which has been elevated to a stable event.
=> add missing LinkEventName for plaid events BANK_INCOME_INSIGHTS_COMPLETED

ios/RNLinksdk.m
`resumeAfterTermination` isn't available in LinkKit `4.1.0` 
So we need to call `[self.linkHandler continueWithRedirectUri:receivedRedirectUri];`
=> [iOS] Fix Compile Issue

PlaidLink.tsx, android/build.gradle, android/src/main/AndroidManifest.xml, ios/RNLinksdk.m, package.json, react-native-plaid-link-sdk.podspec
- Bumps iOS SDK to `4.2.0`
- Bumps Android SDK to `3.11.0`
- Resolves bug in app2app OAuth on iOS.
=> [Release] 10.1.0

ios/RNLinksdk.m
This PR resolves the issue where `PLKLinkEvent` on iOS have camelCase keys while Android has snake_case. To prevent a breaking change both keys are added to the metadata dictionary on iOS. We can deprecate the camelCase keys in the next major release.
**OLD IOS EVENT DATA**
```json
{
"eventName":"TRANSITION_VIEW",
"metadata":{
"errorCode":"",
"errorMessage":"",
"errorType":"",
"exitStatus":"",
"institutionId":"",
"institutionName":"",
"institutionSearchQuery":"",
"linkSessionId":"84a32fb9-67da-4df8-966a-40387c20fd71",
"metadataJson":"",
"mfaType":"",
"requestId":"WUxYDxxmwW8FaIJ",
"timestamp":"2023-05-04T17:57:57.888Z",
"viewName":"CONSENT"
}
}
```
**NEW IOS EVENT DATA**
```json
{
"eventName":"TRANSITION_VIEW",
"metadata":{
"errorCode":"",
"errorMessage":"",
"errorType":"", …
```
=> Fix iOS/Android Event Metadata key formatting

README.md, android/build.gradle, android/src/main/AndroidManifest.xml, example/package.json, ios/RNLinksdk.m, package.json
- Update Android SDK to [3.12.1](https://github.com/plaid/plaid-link-android/releases/tag/v3.12.1).
- [Update Example App](https://github.com/plaid/react-native-plaid-link-sdk/pull/533).
- [Fix event metadata JSON key inconsistency between iOS & Android](https://github.com/plaid/react-native-plaid-link-sdk/pull/532).
=> [Release] - 10.3.0

.github/workflows/build_test_ios.yml, CHANGELOG.md, README.md, android/src/main/AndroidManifest.xml, example/ios/plaidRNDemoTests/PlaidRNDemoTests.swift, ios/RNLinksdk.m, package.json, react-native-plaid-link-sdk.podspec
- Update iOS Native SDK.
- Add support to present Link full screen. `PlaidLinkProps` not supports passing a `LinkIOSPresentationStyle`. Pass `FULL_SCREEN` to present Link full screen instead of as a modal. For more information checkout the [pull-request](https://github.com/plaid/react-native-plaid-link-sdk/pull/543).
Select one:
=> [Release] - 10.5.0

android/build.gradle
Change to support AGP 8 as mentioned here: https://github.com/react-native-community/discussions-and-proposals/issues/671
This does not remove package attribute from AndroidManifest to not lose compatibility with AGP < 8 (React Native < 0.71 versions). 
I don't think it's worth maintaining logic to remove that attribute contitionally since it will [only cause a warning to users on AGP 8](https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1607191009) and above. 
[See Kudo's comment on why we can't set JVM version on Gradle 8](https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1677632448)
Select one:
If you made changes to typescript or javascript you'll need to update the JS bundle in the example app for …
=> feat(android): add support for AGP 8

CHANGELOG.md, ios/RNLinksdk.m
Resolves [Issue 501](https://github.com/plaid/react-native-plaid-link-sdk/issues/501) where we are not sending a `LinkExit` when an invalid token is passed.
Error types should have a consistent format. 
Example LinkExit
```json
{
"error":{
"displayMessage":"self.clientName is , but must be a properly formatted, non-empty string",
"errorCode":"0",
"errorDisplayMessage":"self.clientName is , but must be a properly formatted, non-empty string",
"errorJson":null,
"errorMessage":"self.clientName is , but must be a properly formatted, non-empty string",
"errorType":"creation error",
"metadata":{
"institution":null,
"linkSessionId":null,
"metadataJson":null,
"requestId":null,
"status":null
}
}
}
```
1. Launch the demo app.
2. Press the open Link button (no token)
3. See properly formatted …
=> [Fix] LinkError Type Mismatch (Issue 501)

CHANGELOG.md, README.md, android/src/main/AndroidManifest.xml, ios/RNLinksdk.m, package.json
| React Native | >= [66.0](https://reactnative.dev/blog/2021/10/01/version-066) |
- Resolve Issue [565](https://github.com/plaid/react-native-plaid-link-sdk/issues/565). Where NPM package was in excess of 100mb.
Android SDK [3.14.0](https://github.com/plaid/plaid-link-android/releases/tag/v3.14.0)
iOS SDK [4.6.4](https://github.com/plaid/plaid-link-ios/releases/tag/4.6.4)
| Xcode | >= 14.0 |
| iOS | >= 11.0 |
=> [Release] - 10.6.2

ios/PLKEmbeddedView.swift
If you compile for iOS with Xcode < 14.3 you'll see the following error
>Reference to property 'foo' in closure requires explicit use of 'self' to make capture semantics explicit
[Allow implicit self for weak self captures, after self is unwrapped](https://github.com/apple/swift-evolution/blob/main/proposals/0365-implicit-self-weak-capture.md) covers why this doesn't impact Xcode > 14.3 
So customers can compile with Xcode >= 14.0.1
Select one:
=> [Fix] Xcode < 14.3 Compile Error

CHANGELOG.md, README.md, android/src/main/AndroidManifest.xml, android/src/main/java/com/plaid/gson/RNAccountAdapter.kt, ios/RNLinksdk.m, package.json
Fixes issue [589](https://github.com/plaid/react-native-plaid-link-sdk/issues/589)
Select one:
=> [Release] 10.7.0

CHANGELOG.md, README.md, android/src/main/AndroidManifest.xml, ios/RNLinksdk.m, package.json, src/PlaidLink.tsx, src/Types.ts
- [Resolves Issue 589](https://github.com/plaid/react-native-plaid-link-sdk/issues/598)
- Bumps version to 11.0.1
If a `LinkLogLevel` was not passed into the open call Link would fail to open on Android. 
Select one:
=> [Fix] Issue 598 & Prep 11.0.1

CHANGELOG.md, README.md, android/build.gradle, android/src/main/AndroidManifest.xml, ios/RNLinksdk.m, package.json, src/Types.ts
- Update Android SDK to [3.14.1](https://github.com/plaid/plaid-link-android/releases/edit/v3.14.1) to resolve an Android 14 bug.
- Export `LinkAccountType` and `LinkAccountSubtypes`
Fixes Android 14 bug and allows customers to access more data types per their request.
Select one:
=> [v10] - Update Android SDK and export more types

README.md, src/Types.ts
- Adds clarifying comments about the use of `noLoadingState` in `LinkTokenConfiguration` type.
- Updates readme to state that `noLoadingState` is required.
Flagged as an [issue](https://github.com/plaid/react-native-plaid-link-sdk/issues/614)
Select one:
=> [Fix] Add Clarification around no loading state - Issue 614

CHANGELOG.md, README.md, android/build.gradle, android/src/main/AndroidManifest.xml, ios/RNLinksdk.m, package.json
- Reverts Android SDK SDK to `4.0.0`. To prevent [issue 620](https://github.com/plaid/react-native-plaid-link-sdk/issues/620).
=> [Release] - 11.3.0

CHANGELOG.md, README.md, android/build.gradle, android/src/main/AndroidManifest.xml, ios/RNLinksdk.m, package.json
- Reverts Android SDK SDK to 3.14.2. To prevent issue [620](https://github.com/plaid/react-native-plaid-link-sdk/issues/620).
=> [Release] 10.11.0

CHANGELOG.md, README.md, android/build.gradle, android/src/main/AndroidManifest.xml, ios/RNLinksdk.m, package.json
- Updates Android SDK SDK to 3.14.3. To prevent issue [620](https://github.com/plaid/react-native-plaid-link-sdk/issues/620).
=> [Release] -  10.12.0

CHANGELOG.md, README.md, android/src/main/AndroidManifest.xml, ios/RNLinksdk.m, package.json, react-native-plaid-link-sdk.podspec
- Updates iOS SDK to `5.2.0` for improved Remember Me experience.
Android SDK [4.1.1](https://github.com/plaid/plaid-link-android/releases/tag/v4.1.1)
| Kotlin | 1.8+ |
- Improved Remember Me experience.
iOS SDK [5.2.0](https://github.com/plaid/plaid-link-ios/releases/tag/5.2.0)
| Xcode | >= 15.0.1 |
- Improved Remember Me experience.
=> [Release] 11.5.0

CHANGELOG.md, README.md, android/src/main/AndroidManifest.xml, ios/RNLinksdk.m, package.json
- Resolves bug where `LinkEventMetadata` was undefined on `LinkEvent`. All values inside `LinkEventMetadata` should now be accessible on iOS and Android.
- See [631](https://github.com/plaid/react-native-plaid-link-sdk/pull/631) for more information.
=> [Release] 11.5.1

CHANGELOG.md, README.md, android/src/main/AndroidManifest.xml, ios/RNLinksdk.m, package.json, react-native-plaid-link-sdk.podspec
- Update iOS SDK to [5.2.1](https://github.com/plaid/plaid-link-ios/releases/tag/5.2.1) to provide an improve embedded link experience.
=> [Release] 11.5.2

src/index.ts
Exported the `create` and `open` functions so that they don't need to be imported by deeplinking to the `dist` folder.
Current documentation was unclear on how to actually consume the `create` and `open` functions since the tiny example linked still uses `PlaidLink`. Further examination showed that they were not being exported from `index.ts`. The example in the repo is importing them by deeplinking the `dist` folder.
If alternatives are now deprecated these should be simpler to import.
Import the functions.
Select one:
=> Export create and open functions

CHANGELOG.md, README.md, android/src/main/AndroidManifest.xml, ios/RNLinksdk.mm, package.json
- [Exports added](https://github.com/plaid/react-native-plaid-link-sdk/pull/666) for `create` and `open` functions.
Android SDK [4.4.0](https://github.com/plaid/plaid-link-android/releases/tag/v4.4.0)
- Support Autofill for SMS OTP in Link Sessions using Google play-services-auth-api-phone library version 18.0.2.
- Change LinkActivity to `exported=false`.
| Kotlin | 1.8+ |
iOS SDK [5.5.0](https://github.com/plaid/plaid-link-ios/releases/tag/5.5.0)
- Add PROFILE_DATA_REVIEW view name.
- Add NSPrivacyCollectedDataTypePurposes for NSPrivacyCollectedDataTypeUserID.
| Xcode | >= 15.0.1 |
=> [Release] - 11.10.0

CHANGELOG.md, README.md, android/src/main/AndroidManifest.xml, ios/RNLinksdk.mm, package.json, react-native-plaid-link-sdk.podspec
Android SDK [4.4.0](https://github.com/plaid/plaid-link-android/releases/tag/v4.4.0)
- Support Autofill for SMS OTP in Link Sessions using Google play-services-auth-api-phone library version 18.0.2.
- Change LinkActivity to `exported=false`.
| Kotlin | 1.8+ |
iOS SDK [6.0.0-beta1](https://github.com/plaid/plaid-link-ios/releases/tag/6.0.0-beta1)
- Add support for FinanceKit and Apple card.
| Xcode | >= 15.3.0 |
=> [Release] 12.0.0 beta.1

CHANGELOG.md, README.md, android/src/main/AndroidManifest.xml, ios/RNLinksdk.mm, package.json, react-native-plaid-link-sdk.podspec
Android SDK [4.4.1](https://github.com/plaid/plaid-link-android/releases/tag/v4.4.1)
- Support Autofill for SMS OTP in Link Sessions using Google play-services-auth-api-phone library version 18.0.2.
- Change LinkActivity to `exported=false`.
| Kotlin | 1.8+ |
iOS SDK [5.5.1](https://github.com/plaid/plaid-link-ios/releases/tag/5.5.1)
- Fix headless OAuth bug.
- Improved Remember Me experience.
| Xcode | >= 15.0.1 |
=> [Release] 11.10.2 

CHANGELOG.md, README.md, android/src/main/AndroidManifest.xml, ios/RNLinksdk.m, package.json, react-native-plaid-link-sdk.podspec
| React Native | >= [66.0](https://reactnative.dev/blog/2021/10/01/version-066) |
- Update iOS SDK
Android SDK [3.14.3](https://github.com/plaid/plaid-link-android/releases/tag/v3.14.3)
iOS SDK [4.7.8](https://github.com/plaid/plaid-link-ios/releases/tag/4.7.8)
- Fix headless OAuth bug.
- Improved Remember Me experience.
| Xcode | >= 14.0 |
| iOS | >= 11.0 |
=> [Release] - 10.13.2

CHANGELOG.md, README.md, android/build.gradle, android/src/main/AndroidManifest.xml, android/src/main/java/com/plaid/PlaidModule.kt, android/src/paper/java/com/plaid/NativePlaidLinkModuleAndroidSpec.java, android/src/paper/java/com/plaid/NativePlaidLinkModuleiOSSpec.java, example/ios/Podfile.lock, example/package-lock.json, example/src/Screens/PlaidLinkScreen.tsx, ios/RNLinksdk.mm, package.json, react-native-plaid-link-sdk.podspec, src/PlaidLink.tsx, src/Types.ts, src/fabric/NativePlaidLinkModuleAndroid.ts, src/fabric/NativePlaidLinkModuleiOS.ts, src/index.ts
- Update Android SDK to 4.5.0.
- Update iOS SDK to 5.6.0.
- Add submit API.
=> [Feature] - Add Submit API

ios/PLKFabricHelpers.h, react-native-plaid-link-sdk.podspec
We at [Software Mansion](https://swmansion.com/) have been working on [improving support](https://blog.swmansion.com/sunrising-new-architecture-in-the-new-expensify-app-729d237a02f5) for the new architecture for quite a while now. If you need help with anything related to New Architecture, like:
- [migrating your library](https://x.com/swmansion/status/1717512089323864275)
- [migrating your app](https://github.com/Expensify/App/pull/13767)
- [investigating issues](https://github.com/facebook/react-native/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Aj-piasecki+is%3Aopen)
- [improving performance](https://x.com/BBloniarz_/status/1808138585528303977)
or you just want to ask any questions, hit us up on [projects@swmansion.com](mailto:projects@swmansion.com)
---
Add support for …
=> feat: add use_frameworks support

example/ios/Podfile.lock, example/package-lock.json, example/package.json
Updates the example app to use `11.13.0`
=> [Chore] Update example to Latest SDK

CHANGELOG.md, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, android/src/main/AndroidManifest.xml, ios/RNLinksdk.mm, package-lock.json, package.json
Updates the android compile version to 34.
How to test:
At the root of the project run: 
- start android emulator ex `emulator -avd Pixel_7_API_34`
- npm install
- `tsc && yalc publish && cd example && yalc add react-native-plaid-link-sdk && npm install && npm run android && cd ../`
=> [Fix] Update Android Compile Version to 34

CHANGELOG.md, README.md, android/src/main/AndroidManifest.xml, ios/PLKFabricHelpers.h, ios/RNLinksdk.mm, package.json
Updates to resolve and clarify #713 and #732
=> [Release] - 11.13.3 

CHANGELOG.md, README.md, android/src/main/AndroidManifest.xml, ios/RNLinksdk.mm, package.json, react-native-plaid-link-sdk.podspec, src/fabric/NativePlaidLinkModuleiOS.ts
Resolves #742 and #744 
The `NativePlaidLinkModuleiOS.ts` file has been updated to resolve codegen issues. More specifically `onSuccess: (success: void) => void` was changed to `onSuccess: (success: boolean) => void` and  `onError: (error: FinanceKitError) => void` was changed to `onError: (error: UnsafeObject<FinanceKitError>) => void`.
iOS SDK was also updated to [6.0.2](https://github.com/plaid/plaid-link-ios/releases/tag/6.0.2)
=> [Release] - 12.0.1

CHANGELOG.md, README.md, android/src/main/AndroidManifest.xml, ios/PLKFabricHelpers.h, ios/RNLinksdk.mm, package.json
Fixed: Resolved an issue #747 where the USE_FRAMEWORKS preprocessor check was failing for projects using use_frameworks! :linkage => :static.
Update: Replaced the USE_FRAMEWORKS check with __has_include to properly detect whether the framework is available, ensuring compatibility with both static and dynamic linking configurations.
Impact: This fix allows projects using static frameworks to correctly import react_native_plaid_link_sdk without compilation errors.
=> [Release] 12.0.2

CHANGELOG.md, README.md, android/src/main/AndroidManifest.xml, ios/RNLinksdk.mm, package.json, react-native-plaid-link-sdk.podspec
- Updates iOS SDK to [6.0.4](https://github.com/plaid/plaid-link-ios/releases/tag/6.0.4)
Android SDK [5.0.0](https://github.com/plaid/plaid-link-android/releases/tag/v5.0.0)
- Add AUTO_SUBMIT event name.
- Add INVALID_UPDATE_USERNAME item error.
- Upgrade Kotlin to 1.9.25.
- Upgrade to target and compile SDK version 35.
- Upgrade androidx.databinding:viewbinding library from 8.1.2 to 8.6.1.
- Upgrade androidx.activity:activity library from 1.6.0 to 1.8.2.
- Upgrade androidx.core:core-ktx library from 1.9.0 to 1.13.0.
- Upgrade androidx.fragment:fragment-ktx library from 1.9.0 to 1.13.0.
- Upgrade androidx.room:room-ktx library from 2.6.0 to 2.6.1.
- Upgrade androidx.lifecycle:lifecycle-runtime-ktx library from 2.5.1 to 2.6.1. …
=> [Release] - 12.0.3 

android/src/paper/java/com/facebook/react/viewmanagers/PLKEmbeddedViewManagerDelegate.java
Closes #754
Adds support for react-native 0.77
BaseViewManagerInterface was deleted
https://github.com/facebook/react-native/pull/46809/
Select one:
=> fix: add support for react-native 0.77

CHANGELOG.md, README.md, android/src/main/AndroidManifest.xml, ios/RNLinksdk.mm, package.json, react-native-plaid-link-sdk.podspec
- Updates iOS SDK to [6.1.0](https://github.com/plaid/plaid-link-ios/releases/tag/6.1.0)
- Resolves [issue 754](https://github.com/plaid/react-native-plaid-link-sdk/issues/754)
Android SDK [5.0.0](https://github.com/plaid/plaid-link-android/releases/tag/v5.0.0)
- Add AUTO_SUBMIT event name.
- Add INVALID_UPDATE_USERNAME item error.
- Upgrade Kotlin to 1.9.25.
- Upgrade to target and compile SDK version 35.
- Upgrade androidx.databinding:viewbinding library from 8.1.2 to 8.6.1.
- Upgrade androidx.activity:activity library from 1.6.0 to 1.8.2.
- Upgrade androidx.core:core-ktx library from 1.9.0 to 1.13.0.
- Upgrade androidx.fragment:fragment-ktx library from 1.9.0 to 1.13.0.
- Upgrade androidx.room:room-ktx library from 2.6.0 to …
=> [Release] - 12.1.0

src/PlaidLink.tsx
Remove async def from open
Function definition is inaccurate and misleading since its callback-based and not promise-based
- [yes] I have performed a self-review of my own code.
- [yes] I have optimized code readability (class/variable names, straight forward logic paths, short clarifying docs,...).
- [tested locally in my app] I have manually tested my changes.
Select one:
=> Remove async def from open

android/build.gradle
- the `com.jakewharton.rxrelay2:rxrelay:2.1.1` dependency is not needed. This PR removes it.
=> Remove unused dependency from Android SDK

CHANGELOG.md, README.md, android/build.gradle, android/src/main/AndroidManifest.xml, ios/RNLinksdk.mm, package.json, react-native-plaid-link-sdk.podspec
Android SDK [5.1.1](https://github.com/plaid/plaid-link-android/releases/tag/v5.1.1)
- Add AUTO_SUBMIT event name.
- Add INVALID_UPDATE_USERNAME item error.
- Add Flutter SDK version tracking.
- Fixed edge to edge layout overlap issue in Android 15+.
- Reduced SDK size by 20%, from 6.2 MB down to 5.0 MB.
- Removed org.bouncycastle:bcpkix-jdk15to18 dependency.
| Kotlin | 1.9.25+ (Kotlin integrations only) |
iOS SDK [6.2.1](https://github.com/plaid/plaid-link-ios/releases/tag/6.2.1)
- Add Flutter SDK version tracking.
- Reduced SDK size from 13.2MB to 8.9MB
| Xcode | >= 16.1.0 |
=> [Release] - 12.2.0

CHANGELOG.md, README.md, android/src/main/AndroidManifest.xml, ios/RNLinksdk.mm, ios/RNPlaidHelper.h, ios/RNPlaidHelper.m, package.json, react-native-plaid-link-sdk.podspec, src/PlaidLink.tsx, src/fabric/NativePlaidLinkModuleiOS.ts
Android SDK [5.2.0](https://github.com/plaid/plaid-link-android/releases/tag/v5.2.0)
- Add ISSUE_FOLLOWED, IDENTITY_MATCH_PASSED, and IDENTITY_MATCH_FAILED event names and issue_id event metadata field.
- Improve destroy() API behavior in edge cases.
- Reduce SDK size by 11.5% down from 5.0MB to 4.5MB. 
- Remove the androidx.recyclerview:recyclerview, androidx.constraintlayout:constraintlayout, and io.coil-kt:coil dependencies.
| Kotlin | 1.9.25+ (Kotlin integrations only) |
iOS SDK [6.3.1](https://github.com/plaid/plaid-link-ios/releases/tag/6.3.1)
- Expose Finance Kit sync simulated behavior to Objective-C (React Native).
- Updated Layer submit API
- Added Layer …
=> [Release] - 12.3.1

CHANGELOG.md, README.md, android/build.gradle, android/src/main/AndroidManifest.xml, ios/RNLinksdk.mm, package.json, react-native-plaid-link-sdk.podspec
- Resolved an issue where the `selection` value was missing in `LinkEvent.EventMetadata`.
- Improved internal debugging and logging to help diagnose customer-reported issues more effectively.
- Upgrade to Android SDK [5.4.0](https://github.com/plaid/plaid-link-android/releases/tag/v5.4.0)
- Upgrade to iOS SDK [6.4.1](https://github.com/plaid/plaid-link-ios/releases/tag/6.4.1)
Android SDK [5.4.0](https://github.com/plaid/plaid-link-android/releases/tag/v5.4.0)
- None
- Resolved an issue where the `selection` value was missing in `LinkEvent.EventMetadata`.
- Improved internal debugging and logging to help diagnose customer-reported issues more effectively.
- None
| …
=> 12.6.0 Release
